apiVersion: v1
kind: Service
metadata:
  name: week1-frontend-service
  namespace: week1
spec:
  type: LoadBalancer  # Thay đổi từ ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: week1-frontend